"""Generate the design-system barrel from the vendored primitives.

Reads the real export statements instead of hand-maintaining a list — a
hand-written barrel silently drifts as primitives are added.
"""

import os
import re

UI = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'packages', 'ui', 'src', 'components', 'ui')
UI = os.path.normpath(UI)

TYPE_ONLY = re.compile(r'^type\s+')


def exports_of(path):
    src = open(path, encoding='utf8').read()
    values, types = set(), set()

    # export { A, B as C, type D }
    for block in re.finditer(r'export\s*\{([^}]*)\}(?!\s*from)', src):
        for part in block.group(1).split(','):
            p = part.strip()
            if not p:
                continue
            if TYPE_ONLY.match(p):
                types.add(p[5:].split(' as ')[-1].strip())
            else:
                values.add(p.split(' as ')[-1].strip())

    for m in re.finditer(r'export\s+(?:const|function|class)\s+(\w+)', src):
        values.add(m.group(1))
    for m in re.finditer(r'export\s+(?:interface|type)\s+(\w+)', src):
        types.add(m.group(1))

    return sorted(values), sorted(types)


def main():
    lines = ['/**', ' * Public surface of the design system.', ' *', ]
    lines += [' * GENERATED by scripts/gen-barrel.py — run it after adding a primitive.',
              ' * A hand-maintained barrel drifts; this one is read off the real exports.',
              ' */', '']

    for name in sorted(os.listdir(UI)):
        if not name.endswith(('.ts', '.tsx')) or '.test.' in name:
            continue
        stem = name.rsplit('.', 1)[0]
        values, types = exports_of(os.path.join(UI, name))
        if values:
            lines.append("export { %s } from './components/ui/%s'" % (', '.join(values), stem))
        if types:
            lines.append("export type { %s } from './components/ui/%s'" % (', '.join(types), stem))

    lines += [
        '',
        "export { useMediaQuery } from './hooks/use-media-query'",
        "export { useIsMobile } from './hooks/use-mobile'",
        "export { useResizeObserver } from './hooks/use-resize-observer'",
        '',
        "export { en, I18nProvider, makeTranslations, translateNow, useI18n } from './i18n'",
        "export type { CommonStrings, I18nContextValue, Translations } from './i18n'",
        '',
        "export { registerHapticTrigger, triggerHaptic } from './lib/haptics'",
        "export type { HapticIntent, HapticTrigger } from './lib/haptics'",
        "export { clearKeybinds, getKeybinds, registerKeybinds, useKeybindHint } from './lib/keybinds/use-keybind-hint'",
        "export type { KeybindMap } from './lib/keybinds/use-keybind-hint'",
        "export { comboTokens, formatCombo } from './lib/keybinds/combo'",
        "export { cn } from './lib/utils'",
        '',
        "export * from './theme'",
        '',
    ]

    dst = os.path.normpath(os.path.join(UI, '..', '..', 'index.ts'))
    open(dst, 'w', encoding='utf8', newline='\n').write('\n'.join(lines))
    print('wrote', dst)


if __name__ == '__main__':
    main()
